config/routes.rb
TsetseApp::Application.routes.draw do
  resources :users, :routes, :stations, :sessions

  post '/route_preview', to: 'routes#preview'

  root to: "routes#new"

  get '/signup', to: 'users#new'
  delete '/signout', to: 'sessions#destroy'
  get '/signin', to: 'sessions#new'
end


# Macintosh-2:tsetse_app Flanagan$ rake routes
#       Prefix Verb   URI Pattern                  Controller#Action
#        users GET    /users(.:format)             users#index
#              POST   /users(.:format)             users#create
#     new_user GET    /users/new(.:format)         users#new
#    edit_user GET    /users/:id/edit(.:format)    users#edit
#         user GET    /users/:id(.:format)         users#show
#              PATCH  /users/:id(.:format)         users#update
#              PUT    /users/:id(.:format)         users#update
#              DELETE /users/:id(.:format)         users#destroy
#       routes GET    /routes(.:format)            routes#index
#              POST   /routes(.:format)            routes#create
#    new_route GET    /routes/new(.:format)        routes#new
#   edit_route GET    /routes/:id/edit(.:format)   routes#edit
#        route GET    /routes/:id(.:format)        routes#show
#              PATCH  /routes/:id(.:format)        routes#update
#              PUT    /routes/:id(.:format)        routes#update
#              DELETE /routes/:id(.:format)        routes#destroy
#     stations GET    /stations(.:format)          stations#index
#              POST   /stations(.:format)          stations#create
#  new_station GET    /stations/new(.:format)      stations#new
# edit_station GET    /stations/:id/edit(.:format) stations#edit
#      station GET    /stations/:id(.:format)      stations#show
#              PATCH  /stations/:id(.:format)      stations#update
#              PUT    /stations/:id(.:format)      stations#update
#              DELETE /stations/:id(.:format)      stations#destroy
#     sessions GET    /sessions(.:format)          sessions#index
#              POST   /sessions(.:format)          sessions#create
#  new_session GET    /sessions/new(.:format)      sessions#new
# edit_session GET    /sessions/:id/edit(.:format) sessions#edit
#      session GET    /sessions/:id(.:format)      sessions#show
#              PATCH  /sessions/:id(.:format)      sessions#update
#              PUT    /sessions/:id(.:format)      sessions#update
#              DELETE /sessions/:id(.:format)      sessions#destroy
#         root GET    /                            routes#index
#       signup GET    /signup(.:format)            users#new
#      signout DELETE /signout(.:format)           sessions#destroy
#       signin GET    /signin(.:format)            sessions#new

app/models/route.rb
class Route < ActiveRecord::Base
	belongs_to :user
  has_many :stations
  has_many :users

  # geocoded_by :address
  # after_validation :geocode
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
	include RoutesHelper

	before_filter :signed_in_user, only: [:index, :create, :new, :edit, :update, :destroy]
  before_filter :check_route_owner, only: [:edit, :update, :destroy]

  def index
    @routes = current_user.routes.all
  end

  def new
    @route = Route.new
  end

  def preview
    @route = Route.new(route_params)
    # @stations = @route.stations
    gon.starting_point = @route.starting_point
    gon.end_point = @route.end_point
    @station = Station.all
    gon.station = @station

    # results = Typhoeus.get("http://devapi.mygasfeed.com/stations/radius/37.111363/-121.01662/49/diesel/price/rfej9napna.json?callback=?")
    # gas_man = JSON.parse(results.body)
    # binding.pry
  end  

  def create
    route = current_user.routes.create route_params
    redirect_to(route)
  end

  def show
    @route = current_user.routes.find(id)
    # @stations = @route.stations
    gon.starting_point = @route.starting_point
    gon.end_point = @route.end_point
    # render :show
  end

  def edit
    @route = Route.find(id)
  end

  def update
    route = Route.find(id)
    route.update_attributes route_params
    redirect_to(route)
  end

  def destroy
    route = Route.find(id)
    route.delete
    redirect_to(routes_path)
  end

  private
    def route_params
      params.require(:route).permit(:starting_point, :end_point)
    end

    # Spencer: Cool way to hide your params[:id] into a private method
    def id
      params[:id] 
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
	def check_route_owner
    route = current_user.routes.where(:id => params[:id]).first
    if route.nil?
      flash[:error] = "That's not your route."
      redirect_to route_path(params[:id])
    end
  end
end

app/views/routes/_form.html.erb
	<%= form_for @route, url: route_preview_path do |f| %>
		<%= f.label :starting_point%>
	  <%= f.text_field :starting_point, :id => "starting_point"%>	
	  <br>
	  <%= f.label "Destination:" %>
	  <%= f.text_field :end_point, :autofocus => true, :id => "end_point", :placeholder => "Enter city of address"%>
	  <br>

	  <p><p>
	  <%= f.submit "Submit", class: "btn btn-primary" %>
	<% end %>

app/views/routes/_new_form.html.erb
	<%= form_for @route, url: route_preview_path do |f| %>
	  <%= f.hidden_field :starting_point, :id => "starting_point"%>	
	  <br>
	  <%= f.text_field :end_point, :autofocus => true, :id => "new_end_point", :placeholder => "Enter a city or address", :style => "width: 220px; height: 32px;"%>
	  <br>

	  <p><p>
	  <%= f.submit "Submit", class: "btn btn-success" %>
	<% end %>

app/views/routes/_preview_form.html.erb
	<%= form_for @route do |f| %>
		<%= f.label :starting_point%>
	  <%= f.text_field :starting_point, :id => "starting_point"%>	
	  <br>
	  <%= f.label "Destination:" %>
	  <%= f.text_field :end_point, :autofocus => true, :id => "end_point", :placeholder => "Enter city of address"%>
	  <br>

	  <p><p>
	  <%= f.submit "Save Route", class: "btn btn-primary" %>
	<% end %>

app/views/routes/edit.html.erb
<br>
<br>
<br>
<h1>Edit Route</h1>
<%= render :partial => 'preview_form' %>

app/views/routes/index.html.erb
<body class="index_body">	
	<br>
	<br>
	<br>
	<br>
	<div id="sign_in_head">Saved routes:</div>
	<br>
	<% @routes.each do |route| %>
	  <div class="row">
	     <!-- <div class="col-md-4 col-sm-4"> -->
	      <p class="lead"><%= route.starting_point %> to <%= link_to(route.end_point, route) %>
	    <!-- </div> -->
	    <div class="col-md-8 col-sm-8">
	    </div>
	  </div>
	<% end %>

</div>

app/views/routes/new.html.erb
<body class="turd">	
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>
		<br>

<!-- Spencer: Nice use of partials. -->
<!-- Spencer: That is a lot of <br> tags! There has to be another way. You seem to be good at css so I think you could fix your "turd" class. -->

		<div id="new_destination">
			<div id="new_header"><h1>Destination</h1></div>
		</div>

		<div id="new_formblock">
			<%= render :partial => 'new_form' %>
		</div>
</div>

app/views/routes/preview.html.erb
<body class="preview_body"> 
  <%= render :partial => 'preview_form' %>
    <%= form_for @route do |f| %>
      <%= f.hidden_field :starting_point%>  
      <%= f.hidden_field :end_point%>
    <% end %>


    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <!-- Spencer: Your map styling could be in a style sheet. -->
    <style>
      html, body, #map-canvas {
        height: 100%;
        margin: 10px;
        padding: 30px
      }
    </style>

  <div class="row">
    <div class="col-md-5 col-sm-5">
    </div>
  </div> 


  <!-- ADD MAP OF ROUTE BELOW HERE -->
    <div id="map-canvas"></div>
</div>

app/views/routes/show.html.erb
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <style>
    html, body, #map-canvas {
      height: 100%;
      margin: 10px;
      padding: 30px
    }
  </style>

<body class="index_body"> 
        <div id="show_item">
          <ul class="nav nav-pills">
            <li><%= link_to('Edit route', edit_route_path(@route)) %></li>
            <li><%= link_to('Delete route', @route, :method => :delete, :confirm => 'Are you sure?') %></li>
            <div class='spacer'></div>
          </ul>
        </div>
        <div class="row">
          <!-- <div class="col-md-5 col-sm-5"> -->
            <br>
            <br>
            <div id="sign_in_head">Route:</div>
            <br>
            <div id="show_item"><%= @route.starting_point %>  to <%= @route.end_point %> </div>
            <br>
          <!-- </div> -->
        </div> 

</div>

  <div id="map-canvas"></div>