config/routes.rb
TsetseApp::Application.routes.draw do
  resources :users, :routes, :stations, :sessions

  post '/route_preview', to: 'routes#preview'

  root to: "routes#new"

  get '/signup', to: 'users#new'
  delete '/signout', to: 'sessions#destroy'
  get '/signin', to: 'sessions#new'
end


# Macintosh-2:tsetse_app Flanagan$ rake routes
#       Prefix Verb   URI Pattern                  Controller#Action
#        users GET    /users(.:format)             users#index
#              POST   /users(.:format)             users#create
#     new_user GET    /users/new(.:format)         users#new
#    edit_user GET    /users/:id/edit(.:format)    users#edit
#         user GET    /users/:id(.:format)         users#show
#              PATCH  /users/:id(.:format)         users#update
#              PUT    /users/:id(.:format)         users#update
#              DELETE /users/:id(.:format)         users#destroy
#       routes GET    /routes(.:format)            routes#index
#              POST   /routes(.:format)            routes#create
#    new_route GET    /routes/new(.:format)        routes#new
#   edit_route GET    /routes/:id/edit(.:format)   routes#edit
#        route GET    /routes/:id(.:format)        routes#show
#              PATCH  /routes/:id(.:format)        routes#update
#              PUT    /routes/:id(.:format)        routes#update
#              DELETE /routes/:id(.:format)        routes#destroy
#     stations GET    /stations(.:format)          stations#index
#              POST   /stations(.:format)          stations#create
#  new_station GET    /stations/new(.:format)      stations#new
# edit_station GET    /stations/:id/edit(.:format) stations#edit
#      station GET    /stations/:id(.:format)      stations#show
#              PATCH  /stations/:id(.:format)      stations#update
#              PUT    /stations/:id(.:format)      stations#update
#              DELETE /stations/:id(.:format)      stations#destroy
#     sessions GET    /sessions(.:format)          sessions#index
#              POST   /sessions(.:format)          sessions#create
#  new_session GET    /sessions/new(.:format)      sessions#new
# edit_session GET    /sessions/:id/edit(.:format) sessions#edit
#      session GET    /sessions/:id(.:format)      sessions#show
#              PATCH  /sessions/:id(.:format)      sessions#update
#              PUT    /sessions/:id(.:format)      sessions#update
#              DELETE /sessions/:id(.:format)      sessions#destroy
#         root GET    /                            routes#index
#       signup GET    /signup(.:format)            users#new
#      signout DELETE /signout(.:format)           sessions#destroy
#       signin GET    /signin(.:format)            sessions#new

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    <a class="navbar-brand" href="/routes/new"><img src="http://i.imgur.com/r2rHEXG.jpg"/></a>
    <div id="shark_header">Diesel Shark</div>
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>  
    </button>
  </div>
  <div class="navbar-header navbar-right">
    <% if signed_in? %>
        <ul class="nav nav-pills">
        <li><%= link_to('New route', new_route_path) %></li>
        <li><%= link_to('Saved routes', routes_path) %> </li>   <!-- index -->
        <li><%= link_to('Sign out', signout_path, :method => :delete )%></li>
        <div class='spacer'></div>
        </ul>
    <% else %>
        <p class="navbar-text">
          <%= link_to "Sign up", signup_path %>
        </p>
        <p class="navbar-text">
          <%= link_to "Sign in", signin_path %>
        </p>
    <% end %>

  </div>
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TsetseApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= include_gon %>
</head>
<body>

<%= render 'layouts/header' %>
<br>
<br>
<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, id: "flash_#{name}" %>
<% end %>

<%= yield %>


</body>

<footer>
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true&libraries=places" type="text/javascript"></script>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:700' rel='stylesheet' type='text/css'>
</footer>
</html>